---
- name: Add ufw package
  apt:
    name: ufw
    state: latest
    update_cache: yes

- name: Allow ssh incomming
  ufw:
    rule: allow
    name: OpenSSH

- name: Allow ORPort
  ufw:
    rule: allow
    port: 9001

- name: Enable ufw
  ufw:
    state: enabled
